// Regenerates src/generated/index.ts — a barrel that re-exports every
// ts-rs-generated model. Run automatically as part of `bun run build`.
//
// This exists because ts-rs writes one file per model but never an index,
// so a hand-maintained barrel silently drifts out of sync (it did: Comment,
// ImageCandidate and TopListener were missing). Generating it removes that
// entire class of bug.

import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const genDir = join(here, "..", "src", "generated");

const modules = readdirSync(genDir)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts")
  .map((f) => f.replace(/\.ts$/, ""))
  .sort((a, b) => a.localeCompare(b));

const header =
  "// AUTO-GENERATED by scripts/gen-index.ts — do not edit.\n" +
  "// Re-run with `bun run gen-index` (part of `bun run build`).\n\n";

// NodeNext resolution: the `.js` specifier maps to the sibling `.ts` source
// at compile time and to the emitted `.js` at runtime.
const body = `${modules.map((m) => `export * from "./${m}.js";`).join("\n")}\n`;

writeFileSync(join(genDir, "index.ts"), header + body);
console.log(`gen-index: wrote ${modules.length} re-exports to src/generated/index.ts`);
